# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-12-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('prize', models.IntegerField()),
                ('manufacter', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('filepath', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
