# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_information', '0004_auto_20190211_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_path',
            field=models.CharField(max_length=128),
        ),
    ]
